import {StyleSheet} from 'react-native';
import colors from '../../assets/theme/colors';

export default StyleSheet.create({
  wrapper: {
    paddingHorizontal: 18,
    flex: 1,
    marginTop: 10,
  },
  card: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    elevation: 4,
    marginHorizontal: 16,
    position: 'relative',
    top: -40,
    marginBottom: -35,
  },
  cardTitle: {
    fontSize: 12,
    color: '#FFFFFFCC',
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  cardDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  cardDetailDivider: {width: 0.5, backgroundColor: colors.white},
  sessionTitle: {
    fontSize: 16,
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  title: {
    fontSize: 13,
    // fontWeight: '600',
  //  borderWidth:1,
    marginTop: 5,
    color: '#909090',
    fontFamily: 'Poppins-Bold',
    // borderWidth:1
  },
  apptDateTimeWrapper: {flexDirection: 'row', alignItems: 'center'},
  apptDateTimeIcon: {
    position: 'absolute',
    alignSelf: 'center',
  },
  apptDateTimeValue: {
    fontSize: 13,
    paddingBottom: 4,
    width: '100%',
    paddingStart: 20,
    paddingTop: 4,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
  },
  cutomerCode: {
    borderWidth: 1,
    borderRadius: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    textTransform: 'uppercase',
    paddingVertical: 6,
    marginTop: 6,
    paddingHorizontal: 58,
    fontSize: 13,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
    backgroundColor: colors.cream,
    alignSelf: 'flex-start',
  },
  description: {
    fontSize: 11,
    color: colors.black,
    marginTop: 5,
    // marginLeft:2,
    // borderWidth:1,
    textAlign: 'justify',
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
    
  },
  btnWrapper: {
    flexDirection: 'row',
    flex: 2,
    alignItems: 'flex-end',
    marginBottom: 4,
  },
  btn: {
    flex: 1,
    marginEnd: 6,
    height: 48,
    fontSize: 16,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
  },
  btnArrived: {
    position: 'absolute',
    bottom: 16,
    start: 16,
    end: 16,
    marginTop: 16,
    height: 38,
    fontSize: 16,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
  },
  bsTitle: {
    fontSize: 19,
    alignSelf: 'center',
    // fontWeight: '500',
    marginTop: 35,
    fontFamily: 'Poppins-Regular',
    textTransform: 'capitalize',
  },
  bsSubTitle: {
    fontSize: 12,
    alignSelf: 'center',
    marginTop: 4,
    color: colors.grey,
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  bsApptCodeLbl: {
    fontSize: 13,
    alignSelf: 'center',
    marginTop: 49,
    color: colors.black,
    // fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
  bsApptCode: {
    backgroundColor: colors.cream,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 1,
    fontSize: 17,
    marginTop: 9,
    alignSelf: 'center',
    color: colors.black,
    fontWeight: '600',
    paddingVertical: 20,
    paddingHorizontal: 86,
    fontFamily: 'Poppins-Regular',
  },
  bsCard: {
    backgroundColor: colors.cream,
    paddingTop: 24,
    paddingBottom: 38,
    alignItems: 'center',
    borderRadius: 10,
    marginTop: 32,
    marginHorizontal: 8,
  },
  bsCardTitle: {
    fontWeight: 'bold',
    fontSize: 19,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
  },
  bsDateTimeWrapper: {flexDirection: 'row', alignItems: 'center', marginTop: 6},
  bsBtnWrapper: {
    flexDirection: 'row',
    flex: 2,
    alignItems: 'flex-end',
    marginHorizontal: 8,
    marginTop: 16,
    marginBottom: 10,
  },
  stylistWrapper: {
    // borderWidth: 1,
    borderColor: colors.grey20,
    // paddingHorizontal: 14,
    // marginTop: 8,
    flexDirection:'row'
  },
  stylistName: {

    fontSize: 11,
    color: colors.black,
    marginTop: 5,
    textAlign: 'justify',
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  
    // paddingVertical: 8,
   
  },
  stylistWork: {
    color: colors.black,
    // fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
});
