export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_WARNING = 'MESSAGE_WARNING';
export const MESSAGE_FAUILER = 'MESSAGE_FAUILER';
export const MESSAGE_INFO = 'MESSAGE_INFO';
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR';

export const GET_FCM_TOKEN = 'GET_FCM_TOKEN';
export const GET_TAB_INDEX = 'GET_TAB_INDEX';
export const GET_TAB_VIEW = 'GET_TAB_VIEW';
export const GET_SERVICE_TAB_INDEX = 'GET_SERVICE_TAB_INDEX';
export const GET_POINT_TAB_INDEX = 'GET_POINT_TAB_INDEX';

export const SHOW_BS = 'SHOW_BS';
export const HIDE_BS = 'HIDE_BS';

export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_FAUILER = 'SIGN_UP_FAUILER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAUILER = 'LOGIN_FAUILER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FORGOT_PASS_LOADING = 'FORGOT_PASS_LOADING';
export const FORGOT_PASS_FAUILER = 'FORGOT_PASS_FAUILER';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';

export const VERIFY_OTP_LOADING = 'VERIFY_OTP_LOADING';
export const VERIFY_OTP_FAUILER = 'VERIFY_OTP_FAUILER';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

export const CHANGE_PASS_LOADING = 'CHANGE_PASS_LOADING';
export const CHANGE_PASS_FAUILER = 'CHANGE_PASS_FAUILER';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_FAUILER = 'LOGOUT_FAUILER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const DEACTIVATE_LOADING = 'DEACTIVATE_LOADING';
export const DEACTIVATE_FAUILER = 'DEACTIVATE_FAUILER';
export const DEACTIVATE_SUCCESS = 'DEACTIVATE_SUCCESS';

export const ALREADY_LOGGEDIN = 'ALREADY_LOGGEDIN';

export const GET_UPCOMING_APPTS_LOADING = 'GET_UPCOMING_APPTS_LOADING';
export const GET_UPCOMING_APPTS_FAUILER = 'GET_UPCOMING_APPTS_FAUILER';
export const GET_UPCOMING_APPTS_SUCCESS = 'GET_UPCOMING_APPTS_SUCCESS';
export const GET_MORE_UPCOMMING_APPTS_SUCCESS = 'GET_MORE_UPCOMMING_APPTS_SUCCESS';

export const GET_HISTORY_APPTS_LOADING = 'GET_HISTORY_APPTS_LOADING';
export const GET_HISTORY_APPTS_FAUILER = 'GET_HISTORY_APPTS_FAUILER';
export const GET_HISTORY_APPTS_SUCCESS = 'GET_HISTORY_APPTS_SUCCESS';
export const GET_MORE_HISTORY_APPTS_SUCCESS = 'GET_MORE_HISTORY_APPTS_SUCCESS';

export const GET_SLOT_LOADING = 'GET_SLOT_LOADING';
export const GET_SLOT_FAUILER = 'GET_SLOT_FAUILER';
export const GET_SLOT_SUCCESS = 'GET_SLOT_SUCCESS';

export const UPDATE_APPT_LOADING = 'UPDATE_APPT_LOADING';
export const UPDATE_APPT_FAUILER = 'UPDATE_APPT_FAUILER';
export const UPDATE_APPT_SUCCESS = 'UPDATE_APPT_SUCCESS';

export const CANCEL_APPT_LOADING = 'CANCEL_APPT_LOADING';
export const CANCEL_APPT_FAUILER = 'CANCEL_APPT_FAUILER';
export const CANCEL_APPT_SUCCESS = 'CANCEL_APPT_SUCCESS';

export const DASH_REFRESH_T = 'DASH_REFRESH_T';
export const DASH_REFRESH_F = 'DASH_REFRESH_F';

export const GET_APPT_CODE_LOADING = 'GET_APPT_CODE_LOADING';
export const GET_APPT_CODE_FAUILER = 'GET_APPT_CODE_FAUILER';
export const GET_APPT_CODE_SUCCESS = 'GET_APPT_CODE_SUCCESS';

export const GET_VOUCHER_LOADING = 'GET_VOUCHER_LOADING';
export const GET_VOUCHER_FAUILER = 'GET_VOUCHER_FAUILER';
export const GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS';
export const GET_MORE_VOUCHER_SUCCESS = 'GET_MORE_VOUCHER_SUCCESS';

export const GET_POINTS_HISTORY_LOADING = 'GET_POINTS_HISTORY_LOADING';
export const GET_POINTS_HISTORY_FAUILER = 'GET_POINTS_HISTORY_FAUILER';
export const GET_POINTS_HISTORY_SUCCESS = 'GET_POINTS_HISTORY_SUCCESS';
export const GET_MORE_POINTS_HISTORY_SUCCESS = 'GET_MORE_POINTS_HISTORY_SUCCESS';

export const GET_POINTS_USED_LOADING = 'GET_POINTS_USED_LOADING';
export const GET_POINTS_USED_FAUILER = 'GET_POINTS_USED_FAUILER';
export const GET_POINTS_USED_SUCCESS = 'GET_POINTS_USED_SUCCESS';
export const GET_MORE_POINTS_USED_SUCCESS = 'GET_MORE_POINTS_USED_SUCCESS';

export const GET_HISTORY_VOUCHERS_LOADING = 'GET_HISTORY_VOUCHERS_LOADING';
export const GET_HISTORY_VOUCHERS_FAUILER = 'GET_HISTORY_VOUCHERS_FAUILER';
export const GET_HISTORY_VOUCHERS_SUCCESS = 'GET_HISTORY_VOUCHERS_SUCCESS';
export const GET_MORE_HISTORY_VOUCHERS_SUCCESS = 'GET_MORE_HISTORY_VOUCHERS_SUCCESS';

export const GET_SYSTEM_CONFIG_LOADING = 'GET_SYSTEM_CONFIG_LOADING';
export const GET_SYSTEM_CONFIG_FAUILER = 'GET_SYSTEM_CONFIG_FAUILER';
export const GET_SYSTEM_CONFIG_SUCCESS = 'GET_SYSTEM_CONFIG_SUCCESS';

export const GET_MY_VOUCHER_LOADING = 'GET_MY_VOUCHER_LOADING';
export const GET_MY_VOUCHER_FAUILER = 'GET_MY_VOUCHER_FAUILER';
export const GET_MY_VOUCHER_SUCCESS = 'GET_MY_VOUCHER_SUCCESS';
export const GET_MY_MORE_VOUCHER_SUCCESS = 'GET_MY_MORE_VOUCHER_SUCCESS';


export const BUY_VOUCHER_LOADING = 'BUY_VOUCHER_LOADING';
export const BUY_VOUCHER_FAUILER = 'BUY_VOUCHER_FAUILER';
export const BUY_VOUCHER_SUCCESS = 'BUY_VOUCHER_SUCCESS';

export const BOOK_APPOINTMENT_LOADING = 'BOOK_APPOINTMENT_LOADING';
export const BOOK_APPOINTMENT_FAUILER = 'BOOK_APPOINTMENT_FAUILER';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';

export const BOOK_SERVICES_CHECK_LOADING = 'BOOK_SERVICES_CHECK_LOADING';
export const BOOK_SERVICES_CHECK_FAUILER = 'BOOK_SERVICES_CHECK_FAUILER';
export const BOOK_SERVICES_CHECK_SUCCESS = 'BOOK_SERVICES_CHECK_SUCCESS';

export const GET_DASHBOARD_LOADING = 'GET_DASHBOARD_LOADING';
export const GET_DASHBOARD_FAUILER = 'GET_DASHBOARD_FAUILER';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';

export const GET_GUEST_DASHBOARD_LOADING = 'GET_GUEST_DASHBOARD_LOADING';
export const GET_GUEST_DASHBOARD_FAUILER = 'GET_GUEST_DASHBOARD_FAUILER';
export const GET_GUEST_DASHBOARD_SUCCESS = 'GET_GUEST_DASHBOARD_SUCCESS';

export const GET_BANNER_LOADING = 'GET_BANNER_LOADING';
export const GET_BANNER_FAUILER = 'GET_BANNER_FAUILER';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_FAUILER = 'GET_PROFILE_FAUILER';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const GET_SERVICES_LOADING = 'GET_SERVICES_LOADING';
export const GET_SERVICES_FAUILER = 'GET_SERVICES_FAUILER';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_MORE_SERVICES_SUCCESS = 'GET_MORE_SERVICES_SUCCESS';

export const GET_HISTORY_SERVICES_LOADING = 'GET_HISTORY_SERVICES_LOADING';
export const GET_HISTORY_SERVICES_FAUILER = 'GET_HISTORY_SERVICES_FAUILER';
export const GET_HISTORY_SERVICES_SUCCESS = 'GET_HISTORY_SERVICES_SUCCESS';
export const GET_MORE_HISTORY_SERVICES_SUCCESS = 'GET_MORE_HISTORY_SERVICES_SUCCESS';
