import {StyleSheet} from 'react-native';
import colors from '../../assets/theme/colors';

export default StyleSheet.create({
  wrapper: {
    paddingHorizontal: 18,
    flex: 1,
  },
  card: {
    backgroundColor: colors.cream,
    borderRadius: 12,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor:'#e5bad8',
    overflow: 'hidden',
    flexDirection: 'column',
    margin: 6,
    paddingTop: 20,
    paddingBottom: 10,
    alignItems: 'center',
    marginHorizontal: 16,
    top: -50,
    marginBottom: -45,
  },
  vCardOfferMessage: {
    fontSize: 25,
    color: colors.primary,
    // fontWeight: '600',
    fontFamily: 'Poppins-Bold',
  },
  vCardOfferOnMessage: {
    fontSize: 14,
    color: colors.black,
    fontFamily: 'Poppins-Regular',
    padding: 5,

  },
  vCardValidity: {
    fontSize: 10,
    marginTop: 20,
    color: colors.grey,
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  title: {
    fontSize: 13,
    marginTop: 12,
    fontFamily: 'Poppins-Regular',
  },
  description: {
    fontSize: 11,
    color: colors.grey,
    marginTop: 6,
    textAlign: 'justify',
    // fontWeight: '400',
    fontFamily: 'Poppins-Regular',
  },
  temsAndCondition: {
    fontSize: 9,
    marginTop: 6,
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
    color: 'blue',
    textDecorationLine: 'underline',
  },
  btn: {
    fontSize: 13,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
    minHeight: 46,
    position: 'absolute',
    bottom: 14,
    start: 18,
    end: 18,
  },
  bsTitle: {
    fontSize: 19,
    alignSelf: 'center',
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  bsSubTitle: {
    fontSize: 12,
    alignSelf: 'center',
    marginTop: 4,
    color: colors.grey,
    // fontWeight: '500',
    fontFamily: 'Poppins-Regular',
  },
  bsCard: {
    borderRadius: 12,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: colors.primary,
    marginTop: 8,
    overflow: 'hidden',
    paddingTop: 20,
    alignItems: 'center',
    marginHorizontal: 16,
    flex: 1,
  },
  bsCardPoints: {
    fontSize: 17,
    color: colors.primary,
    // fontWeight: '600',
    marginTop: 16,
    backgroundColor: colors.cream,
    textAlign: 'center',
    width: '100%',
    height: 30,
    fontFamily: 'Poppins-SemiBold',
    textAlignVertical: 'center',
  },
  bsRemainingPointLbl: {
    fontSize: 10,
    // fontWeight: '500',
    color: colors.black,
    marginTop: 20,
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  bsRemainingPoint: {
    fontSize: 20,
    // fontWeight: '600',
    color: colors.primary,
    alignSelf: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  bsBtnWrapper: {
    flexDirection: 'row',
    flex: 2,
    alignItems: 'flex-end',
    marginHorizontal: 8,
    marginTop: 16,
    marginBottom: 10,
  },
  bsBtn: {
    flex: 1,
    marginEnd: 6,
    height: 48,
    fontSize: 16,
    // fontWeight: '600',
    fontFamily: 'Poppins-Regular',
  },
});
